spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CDM3
    username: postgres
    password: cdm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      show_sql: true
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        type: trace